// Code generated by "stringer -type mode,name"; DO NOT EDIT.

package ccgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[void-0]
	_ = x[lvalue-1]
	_ = x[value-2]
	_ = x[call-3]
}

const _mode_name = "voidlvaluevaluecall"

var _mode_index = [...]uint8{0, 4, 10, 15, 19}

func (i mode) String() string {
	if i < 0 || i >= mode(len(_mode_index)-1) {
		return "mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mode_name[_mode_index[i]:_mode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[external-0]
	_ = x[typename-1]
	_ = x[importQualifier-2]
	_ = x[macro-3]
	_ = x[define-4]
	_ = x[staticInternal-5]
	_ = x[staticNone-6]
	_ = x[automatic-7]
	_ = x[preserve-8]
}

const _name_name = "externaltypenameimportQualifiermacrodefinestaticInternalstaticNoneautomaticpreserve"

var _name_index = [...]uint8{0, 8, 16, 31, 36, 42, 56, 66, 75, 83}

func (i name) String() string {
	if i < 0 || i >= name(len(_name_index)-1) {
		return "name(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _name_name[_name_index[i]:_name_index[i+1]]
}
