// Code generated by "stringer -type mode,name"; DO NOT EDIT.

package ccgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[void-0]
	_ = x[lvalue-1]
	_ = x[value-2]
	_ = x[call-3]
}

const _mode_name = "voidlvaluevaluecall"

var _mode_index = [...]uint8{0, 4, 10, 15, 19}

func (i mode) String() string {
	if i < 0 || i >= mode(len(_mode_index)-1) {
		return "mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mode_name[_mode_index[i]:_mode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[define-0]
	_ = x[enumConst-1]
	_ = x[external-2]
	_ = x[internal-3]
	_ = x[macro-4]
	_ = x[none-5]
	_ = x[taggedEum-6]
	_ = x[taggedStruct-7]
	_ = x[taggedUnion-8]
	_ = x[typename-9]
	_ = x[unpinned-10]
}

const _name_name = "defineenumConstexternalinternalmacrononetaggedEumtaggedStructtaggedUniontypenameunpinned"

var _name_index = [...]uint8{0, 6, 15, 23, 31, 36, 40, 49, 61, 72, 80, 88}

func (i name) String() string {
	if i < 0 || i >= name(len(_name_index)-1) {
		return "name(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _name_name[_name_index[i]:_name_index[i+1]]
}
