// Code generated by "stringer -output stringer.go -type mode,name"; DO NOT EDIT.

package ccgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[void-0]
	_ = x[lvalue-1]
	_ = x[value-2]
	_ = x[call-3]
}

const _mode_name = "voidlvaluevaluecall"

var _mode_index = [...]uint8{0, 4, 10, 15, 19}

func (i mode) String() string {
	if i < 0 || i >= mode(len(_mode_index)-1) {
		return "mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mode_name[_mode_index[i]:_mode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[external-0]
	_ = x[typename-1]
	_ = x[taggedStruct-2]
	_ = x[importQualifier-3]
	_ = x[macro-4]
	_ = x[define-5]
	_ = x[staticInternal-6]
	_ = x[staticNone-7]
	_ = x[automatic-8]
	_ = x[ccgoAutomatic-9]
	_ = x[preserve-10]
}

const _name_name = "externaltypenametaggedStructimportQualifiermacrodefinestaticInternalstaticNoneautomaticccgoAutomaticpreserve"

var _name_index = [...]uint8{0, 8, 16, 28, 43, 48, 54, 68, 78, 87, 100, 108}

func (i name) String() string {
	if i < 0 || i >= name(len(_name_index)-1) {
		return "name(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _name_name[_name_index[i]:_name_index[i+1]]
}
