// Code generated by 'v3 -host-config-opts=-std=c2x,-march=native,-mtune=skylake-avx512,-arch=x86_64,-m64 -err-trace -pkgname=lzfse -trace-translation-units -hide=fse_extract_bits64 -o lib/lzfse/lzfse_darwin_amd64.go -I~/src/github.com/lzfse/lzfse/src -DHAVE_LABELS_AS_VALUES=0 /Users/zchee/src/github.com/lzfse/lzfse/src/lzvn_decode_base.c /Users/zchee/src/github.com/lzfse/lzfse/src/lzfse_encode.c /Users/zchee/src/github.com/lzfse/lzfse/src/lzfse_decode_base.c /Users/zchee/src/github.com/lzfse/lzfse/src/lzfse_decode.c /Users/zchee/src/github.com/lzfse/lzfse/src/lzfse_fse.c /Users/zchee/src/github.com/lzfse/lzfse/src/lzvn_encode_base.c /Users/zchee/src/github.com/lzfse/lzfse/src/lzfse_encode_base.c', DO NOT EDIT.

package lzfse

var CAPI = map[string]struct{}{
	"__builtin_ctzl":                   {},
	"__builtin_ctzll":                  {},
	"__darwin_check_fd_set_overflow":   {},
	"fse_init_decoder_table":           {},
	"fse_init_encoder_table":           {},
	"fse_init_value_decoder_table":     {},
	"fse_normalize_freq":               {},
	"lzfse_decode":                     {},
	"lzfse_decode_buffer":              {},
	"lzfse_decode_buffer_with_scratch": {},
	"lzfse_decode_scratch_size":        {},
	"lzfse_encode_base":                {},
	"lzfse_encode_buffer":              {},
	"lzfse_encode_buffer_with_scratch": {},
	"lzfse_encode_finish":              {},
	"lzfse_encode_init":                {},
	"lzfse_encode_scratch_size":        {},
	"lzfse_encode_translate":           {},
	"lzvn_decode":                      {},
	"lzvn_encode":                      {},
	"lzvn_encode_buffer":               {},
	"lzvn_encode_scratch_size":         {},
}
