// Code generated by "stringer -output stringer.go -type=exprMode"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[exprAddrOf-1]
	_ = x[exprBool-2]
	_ = x[exprLValue-3]
	_ = x[exprPSelect-4]
	_ = x[exprPointer-5]
	_ = x[exprSelect-6]
	_ = x[exprValue-7]
	_ = x[exprVoid-8]
}

const _exprMode_name = "exprAddrOfexprBoolexprLValueexprPSelectexprPointerexprSelectexprValueexprVoid"

var _exprMode_index = [...]uint8{0, 10, 18, 28, 39, 50, 60, 69, 77}

func (i exprMode) String() string {
	i -= 1
	if i < 0 || i >= exprMode(len(_exprMode_index)-1) {
		return "exprMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _exprMode_name[_exprMode_index[i]:_exprMode_index[i+1]]
}
